site_name: ConvoSphere
site_description: Modern, full-stack AI assistant platform with FastAPI backend and React frontend
site_author: ConvoSphere Development Team
site_url: https://convosphere.github.io/convosphere/

repo_name: ConvoSphere/ConvoSphere
repo_url: https://github.com/ConvoSphere/ConvoSphere
edit_uri: edit/main/docs/

docs_dir: docs

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - toc.follow
    - toc.integrate
    - top
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - mermaid2
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      enable_parallel_processing: false
      enable_git_follow: false
  - minify:
      minify_html: true
  - awesome-pages
  - section-index

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ConvoSphere/ConvoSphere
    - icon: fontawesome/brands/discord
      link: https://discord.gg/your-server
  version:
    provider: mike
  analytics:
    provider: google
    property: ""  # Set your Google Analytics key here

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - User Guide: user-guide.md
  - Developer Guide: developer-guide.md
  - Architecture: architecture.md
  - API Reference: api.md
  - Knowledge Base:
    - Settings: KNOWLEDGE_BASE_SETTINGS.md
    - RAG Features: RAG_FEATURES.md
    - Bulk Operations: BULK_OPERATIONS.md
    - Storage Integration: STORAGE_INTEGRATION.md
  - Security: security.md
  - Changelog: changelog.md
  - FAQ: faq.md
  - Development:
    - Overview: development/README.md
    - Implementation Summary: development/IMPLEMENTATION_SUMMARY.md
    - User Management: development/USER_MANAGEMENT_IMPLEMENTATION.md
    - Design System: development/DESIGN_SYSTEM.md
    - Extended Export Features: development/EXTENDED_EXPORT_FEATURES.md
    - Integration Summary: development/INTEGRATION_SUMMARY.md
    - Improvements Summary: development/IMPROVEMENTS_SUMMARY.md
    - Refactoring Summary: development/REFACTORING_SUMMARY.md
    - Test Coverage:
      - Improvement Plan: development/test_coverage_improvement_plan.md
      - Quick Start: development/test_coverage_quick_start.md
  - Analysis:
    - Overview: analysis/README.md
    - Technical Analysis Summary: analysis/TECHNICAL_ANALYSIS_SUMMARY.md
  - Reports:
    - Overview: reports/README.md
    - Code Quality Summary: reports/CODE_QUALITY_SUMMARY.md
    - Test Results: reports/test_results_summary.md
  - Agent Implementation: agent-implementation.md 