site_name: AI Chat Application
site_description: Modern, full-stack AI chat application with FastAPI backend and React frontend
site_author: AI Chat Development Team
site_url: https://lichtbaer.github.io/ai-chat-app/

repo_name: lichtbaer/ai-chat-app
repo_url: https://github.com/lichtbaer/ai-chat-app
edit_uri: edit/main/docs/

docs_dir: docs

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - toc.follow
    - toc.integrate
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png

# Internationalization
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Deutsch
      link: /de/
      lang: de
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      # auto_append:
      #   - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - toc:
      permalink: true
      title: On this page
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

plugins:
  - search
  - mermaid2:
      arguments:
        theme: default
        themeVariables:
          primaryColor: '#3f51b5'
          primaryTextColor: '#fff'
          primaryBorderColor: '#3f51b5'
          lineColor: '#3f51b5'
          secondaryColor: '#f50057'
          tertiaryColor: '#f0f0f0'
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      fallback_to_build_date: true
      enable_parallel_processing: false
  - minify:
      minify_html: true
  - awesome-pages
  - section-index

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/ai-chat-app
    - icon: fontawesome/brands/discord
      link: https://discord.gg/your-server
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/your-org
  version:
    provider: mike
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - User Guide: user-guide.md
  - FAQ: faq.md
  - Developer Guide: developer-guide.md
  - API Reference: api-reference.md
  - Deployment: deployment.md
  - Project:
    - Status: project/status.md
    - Changelog: project/changelog.md
    - Contributing: project/contributing.md
  - Deutsch:
    - Startseite: de/index.md
    - Quick Start: de/quick-start.md
    - Benutzer-Guide: de/user-guide.md
    - FAQ: de/faq.md
    - Entwickler-Guide: de/developer-guide.md 