site_name: ConvoSphere
site_description: Modern, full-stack AI assistant platform with FastAPI backend and React frontend
site_author: ConvoSphere Development Team
site_url: https://convosphere.github.io/convosphere/

repo_name: ConvoSphere/ConvoSphere
repo_url: https://github.com/ConvoSphere/ConvoSphere
edit_uri: edit/main/docs/

docs_dir: docs

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - toc.follow
    - toc.integrate
    - top
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - mermaid2
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      enable_parallel_processing: false
      enable_git_follow: false
  - minify:
      minify_html: true
  - awesome-pages
  - section-index

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ConvoSphere/ConvoSphere
    - icon: fontawesome/brands/discord
      link: https://discord.gg/your-server
  version:
    provider: mike
  analytics:
    provider: google
    property: ""  # Set your Google Analytics key here

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - User Guide: user-guide.md
  - Developer Guide: developer-guide.md
  - Architecture: architecture.md
  - API Reference: api.md
  - Security: security.md
  - Changelog: changelog.md
  - FAQ: faq.md
  - Development:
    - Test Coverage: development/test_coverage_improvement_plan.md
    - Test Quick Start: development/test_coverage_quick_start.md
    - Implementation Summaries:
      - Phase 1: development/PHASE1_IMPLEMENTATION_SUMMARY.md
      - Phase 2: development/PHASE2_IMPLEMENTATION_SUMMARY.md
      - Phase 3: development/PHASE3_IMPLEMENTATION_SUMMARY.md
      - Phase 4: development/PHASE4_IMPLEMENTATION_SUMMARY.md
      - Phase 5: development/PHASE5_EXTENDED_EXPORT_SUMMARY.md
    - Design & Architecture:
      - Design System: development/DESIGN_SYSTEM.md
      - Extended Export Features: development/EXTENDED_EXPORT_FEATURES.md
      - Integration Summary: development/INTEGRATION_SUMMARY.md
      - Improvements Summary: development/IMPROVEMENTS_SUMMARY.md
      - Refactoring Summary: development/REFACTORING_SUMMARY.md
      - User Management Implementation: development/Benutzerverwaltung_Implementierung.md
    - Agent Implementation: agent-implementation.md
  - Analysis:
    - Database Analysis: analysis/sqlite_vs_postgresql_analysis.md
    - Translation Analysis: analysis/translation_analysis_report.md
    - Translation Improvements: analysis/translation_improvements_summary.md
  - Reports:
    - Overview: reports/README.md
    - Code Quality:
      - Type Fixes Summary: reports/code-quality/type_fixes_summary.md
      - Service Layer Type Fixes: reports/code-quality/service_layer_type_fixes.md
      - MyPy Analysis Report: reports/code-quality/mypy_analysis_report.md
      - Code Quality Report: reports/code-quality/code_quality_report.md
      - Complete Type Analysis: reports/code-quality/complete_type_analysis_final.md
      - Fixes Summary: reports/code-quality/fixes_summary.md
      - Final Type Fixes Summary: reports/code-quality/final_type_fixes_summary.md
    - Development:
      - Next Steps Completed: reports/development/next_steps_completed.md
      - Development Priorities: reports/development/priorities.md
      - GitHub Actions Fixes: reports/development/GITHUB_ACTIONS_FIXES.md
    - Test Results: reports/test_results_summary.md 