target-version = "py39"
line-length = 88
select = [
    "E", "F", "I", "N", "W", "C4", "UP", "ARG", "SIM", 
    "TCH", "Q", "RSE", "RET", "SLF", "SLOT", "TID", "PIE", 
    "PYI", "PT", "LOG", "PTH", "ERA", "PD", "PGH", "PL", 
    "TRY", "NPY", "AIR", "PERF", "FURB", "BLE"
]
ignore = ["E501"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
