"""Initial migration

Revision ID: ad2434bca38f
Revises:
Create Date: 2025-07-03 10:11:38.374061

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ad2434bca38f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
