"""add_message_reactions_table

Revision ID: b4129b480bce
Revises: c02ce5c4f07b
Create Date: 2025-07-08 21:41:20.691020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4129b480bce'
down_revision: Union[str, Sequence[str], None] = 'c02ce5c4f07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('archived_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'archived_at')
    # ### end Alembic commands ###
