"""Create all tables

Revision ID: c02ce5c4f07b
Revises: ad2434bca38f
Create Date: 2025-07-03 23:32:51.718813

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c02ce5c4f07b"
down_revision: str | Sequence[str] | None = "ad2434bca38f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
