site_name: AI Assistant Platform
site_description: Comprehensive AI Assistant Platform with FastAPI backend and modular architecture
site_author: Development Team
site_url: https://github.com/your-org/chatassistant

repo_name: chatassistant
repo_url: https://github.com/your-org/chatassistant
edit_uri: edit/main/docs/

docs_dir: .

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasks
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - mermaid2
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/chatassistant
    - icon: fontawesome/brands/discord
      link: https://discord.gg/your-server

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Architecture:
    - Overview: architecture/overview.md
    - Backend: architecture/backend.md
    - Frontend: architecture/frontend.md
    - Database: architecture/database.md
  - Development:
    - Setup: development/setup.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
    - Code Style: development/code-style.md
  - API Reference:
    - Overview: api/overview.md
    - Authentication: api/authentication.md
    - Endpoints: api/endpoints.md
    - Models: api/models.md
  - Features:
    - AI Integration: features/ai-integration.md
    - Internationalization: features/internationalization.md
    - Security: features/security.md
    - Tools: features/tools.md
  - Deployment:
    - Docker: deployment/docker.md
    - Production: deployment/production.md
    - Monitoring: deployment/monitoring.md
  - Project:
    - Status: project/status.md
    - Roadmap: project/roadmap.md
    - Changelog: project/changelog.md 